import { registerLicense } from "@syncfusion/ej2-base"
import "../scss/global.scss"
import AuthProvider from '../components/auth-provider'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

registerLicense(process.env.LICENCE_KEY)

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          {children}
        </body>
      </AuthProvider>
    </html>
  )
}
